version: '3'

services:
    db:
        build: ./database
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
    python-app:
        build: ./backend
        container_name: backend
        ports:
            - "5000:5000"  
        depends_on:
            - db
    nginx:
        build: ./nginx
        container_name: nginx
        ports:
            - "80:80" 
        depends_on:
            - python-app
    
        
